sudo: required
language: ruby

services:
  mongodb
  docker

before_install:
  - docker build --tag login .
  - docker run login -c "gulp test"

script:
  - docker ps -a

branches:
  only:
    - master
    - production

notifications:
  slack: wrioos:XDZWFBrf9TDtoEOcw5YGBM4a

deploy:
  - provider: s3
    access_key_id:
      secure: E8UFms7+Xv7PxCT3kybFHGI44O2g9KehUdEkddQaYyxNYrQD9RQyHi7kMXO42kWUHzYeM3k5OAvJKpXj463amMMES4rxP1h557F1DBb5Z3DrA+4ubSsq/LlCNI8Dc80xZhgf1ZDs+b0Ld2AyxMcfB1Ca7fBcVVIGkq5zzqTQ9fg=
    secret_access_key:
      secure: iYeo/OGPNjMRkx+FIMtCRRHenR5cU+5p/JSFRIEtpyYo1PD68Hnlaornaj379RazR1IlV1Vmr6vlnvzjOOJIZeB36jQ5nvYgP2oicWiDlvm2VWSIQVR3ehLkk3wZnZ9yd1phM/QyCiSIQ5/PgUJm49owWjmquaeZbzwoxy39JsE=
    bucket: wrioos.com
    upload-dir: Login-WRIO-App
    acl: public_read
    on:
      repo: webRunes/Login-WRIO-App
      branch: production
